"""empty message

Revision ID: a589161191f2
Revises: 4c25ea9f4ea8
Create Date: 2023-03-11 18:11:28.646550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a589161191f2'
down_revision = '4c25ea9f4ea8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author', sa.String(length=54), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=54), nullable=True))
        batch_op.add_column(sa.Column('pages', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('publishCompany', sa.String(length=54), nullable=True))
        batch_op.create_index(batch_op.f('ix_books_author'), ['author'], unique=False)
        batch_op.create_index(batch_op.f('ix_books_category'), ['category'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_category'))
        batch_op.drop_index(batch_op.f('ix_books_author'))
        batch_op.drop_column('publishCompany')
        batch_op.drop_column('pages')
        batch_op.drop_column('category')
        batch_op.drop_column('author')

    # ### end Alembic commands ###
